# cpanel.yml
# No-op deployment script for Laravel plugin package

name: Filametrics Plugin (No Deployment Steps Needed)

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Nothing to deploy (plugin only)
        run: echo "This is a Laravel plugin, no deploy steps required."
